version: '3.1'
services:
  db:
    image: postgres:15
    container_name: pg-15
    ports:
      - "5400:5432"
    networks:
      - network-odoo-19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  network-odoo-19: